name: thailandhightwaycamerav1
description: A new Flutter project.

publish_to: 'none' 

version: 3.0.0+4

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flex_color_scheme: ^6.1.2
  font_awesome_flutter: ^10.3.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  geolocator: ^9.0.1
  fluttertoast: ^8.1.2
  connectivity_plus: ^3.0.2
  flutter_speed_dial: ^6.2.0
  url_launcher: ^6.1.8
  package_info_plus: ^3.0.2
  percent_indicator: ^4.2.2
  hexcolor: ^3.0.1
  permission_handler: ^10.2.0
  app_settings: 4.2.0
  better_player: ^0.0.83
  flutter_dotenv: ^5.1.0


dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"


flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - .env

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
